### ISSUE TITLE
Posting an email leads always to an error response

### ISSUE THREAD

**Issue by rmeissn** [HTWK-App/Server-Application#49]
If you're posting an email by https://htwk-app.imn.htwk-leipzig.de/mailbox/send?credentials=CHANGEME&salt=CHANGEME&to=CHANGEME&cc=&subject=Test&message=Test&from=CHANGEME_for.surname@htwk-leipzig.de to the HTWK-App Server (with your right email adress), you'll always get a response like:

{
"message":"Invalid Addresses",

"exception":"javax.mail.SendFailedException: Invalid Addresses;\n  nested exception is:\n\tcom.sun.mail.smtp.SMTPAddressFailedException: 550 5.1.7 <for.surname@htwk-leipzig.de>: Sender address rejected: undeliverable address: host MAIL.htwk-leipzig.de[141.57.1.8] said: 554 5.7.1 <for.surname@htwk-leipzig.de>: Recipient address rejected: No such user in htwk-leipzig.de (in reply to RCPT TO command)\n",

"url":"http://htwk-app.imn.htwk-leipzig.de/mailbox/send"
}

This shouldn't happen if someone uses the pattern: for.surname@htwk-leipzig.de

Btw: The ERROR response was delivered with Status code OK(200)....it should be NotFound or something alike.

**Comment by hknochi** [comment]
if you switch to the feature/springBoot branch this will work fine
