### ISSUE TITLE
Exception response on QIS

### ISSUE THREAD

**Issue by rmeissn** [HTWK-App/Server-Application#55]
If I fetch from https://htwk-app.imn.htwk-leipzig.de/qis/get?credentials=XXX&salt=YYY (with right cred. and salt), all I get is:

```
{
	"message":null,
	"exception":"java.lang.NullPointerException",
	"url":"http://htwk-app.imn.htwk-leipzig.de/qis/get"
}
```

This is not supposed to happen!

**Comment by hknochi** [comment]
if you switch to the feature/springBoot branch this will work fine
